"""Settings and Indexes

Revision ID: 478ce279880c
Revises: e4de7a96d53b
Create Date: 2026-09-18 16:46:14.698599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '478ce279880c'
down_revision: Union[str, Sequence[str], None] = 'e4de7a96d53b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=120), nullable=False),
    sa.Column('support_phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('zip_code', sa.String(length=20), nullable=False),
    sa.Column('vat_percentage', sa.Numeric(precision=5, scale=2), server_default=sa.text('10'), nullable=False),
    sa.Column('care_oil_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('120000'), nullable=False),
    sa.Column('care_oil_enabled', sa.Boolean(), nullable=False),
    sa.Column('signature_packaging_price', sa.Numeric(precision=10, scale=2), server_default=sa.text('185000'), nullable=False),
    sa.Column('signature_packaging_enabled', sa.Boolean(), nullable=False),
    sa.Column('shipping_methods', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_status'), 'orders', ['status'], unique=False)
    op.create_index(op.f('ix_products_is_active'), 'products', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_is_active'), table_name='products')
    op.drop_index(op.f('ix_orders_status'), table_name='orders')
    op.drop_table('store_settings')
    # ### end Alembic commands ###
