"""Refactor schemas

Revision ID: e4de7a96d53b
Revises: 750443df651d
Create Date: 2026-09-18 12:58:39.697534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4de7a96d53b'
down_revision: Union[str, Sequence[str], None] = '750443df651d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('image_url', sa.String(length=512), nullable=True))
    op.add_column('orders', sa.Column('shipping_method', sa.String(length=60), nullable=True))
    op.add_column('products', sa.Column('images', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('products', sa.Column('profit_margin', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.drop_column('products', 'main_image_url')
    op.drop_column('products', 'hover_image_url')
    op.add_column('promo_codes', sa.Column('min_purchase_amount', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('province', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('address', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'zip_code')
    op.drop_column('users', 'city')
    op.drop_column('users', 'province')
    op.drop_column('promo_codes', 'min_purchase_amount')
    op.add_column('products', sa.Column('hover_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('main_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('products', 'profit_margin')
    op.drop_column('products', 'images')
    op.drop_column('orders', 'shipping_method')
    op.drop_column('categories', 'image_url')
    # ### end Alembic commands ###
